
import { GeneratedArt, AnimationSettings } from '../domain/entities';

export function generateKotlinFleksCode(art: GeneratedArt, settings: AnimationSettings): string {
  const words = art.prompt.split(/[^a-zA-Z0-9]/).filter(w => w.length > 0).slice(0, 3);
  let safeName = 'entity';
  
  if (words.length > 0) {
    safeName = words.map((w, i) => 
      i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()
    ).join('');
  }

  const { rows, cols, targetResolution, fps } = settings;
  const totalFrames = rows * cols;
  const durationMs = Math.round(1000 / fps);
  
  const framesList = Array.from({length: totalFrames}, (_, i) => i).join(', ');

  let code = `// Generated by PixelForge (Fleks ECS)\n`;
  code += `val ${safeName} = world.entity {\n`;
  code += `    it += SpriteComponent(\n`;
  code += `        texture = resources.${safeName}Texture,\n`;
  code += `        slice = Slice(x = 0, y = 0, w = ${targetResolution}, h = ${targetResolution})\n`;
  code += `    )\n`;
  
  if (totalFrames > 1) {
    code += `    it += AnimationComponent(\n`;
    code += `        frames = listOf(${framesList}),\n`;
    code += `        frameDuration = ${durationMs}.milliseconds\n`;
    code += `    )\n`;
  }
  
  if (art.sliceData) {
     code += `    \n    // 9-Slice Configuration\n`;
     code += `    it += NineSliceComponent(\n`;
     code += `        top = ${art.sliceData.top}, bottom = ${art.sliceData.bottom},\n`;
     code += `        left = ${art.sliceData.left}, right = ${art.sliceData.right}\n`;
     code += `    )\n`;
  }
  
  code += `}`;
  return code;
}

export function generateComposeCode(art: GeneratedArt, settings: AnimationSettings): string {
  const words = art.prompt.split(/[^a-zA-Z0-9]/).filter(w => w.length > 0).slice(0, 3);
  let baseName = 'pixel_asset';
  
  if (words.length > 0) {
    baseName = words.map(w => w.toLowerCase()).join('_');
  }
  
  const componentName = baseName.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');

  let code = `// Generated by PixelForge (Compose Multiplatform)\n`;
  code += `import androidx.compose.foundation.Image\n`;
  code += `import androidx.compose.runtime.Composable\n`;
  code += `import androidx.compose.ui.Modifier\n`;
  code += `import androidx.compose.ui.layout.ContentScale\n`;
  code += `import androidx.compose.ui.unit.dp\n`;
  code += `import org.jetbrains.compose.resources.painterResource\n\n`;
  
  code += `@Composable\n`;
  code += `fun ${componentName}Sprite(\n`;
  code += `    modifier: Modifier = Modifier\n`;
  code += `) {\n`;
  // SECURITY: Sanitize prompt to prevent code injection in exported Kotlin file
  const safeDescription = art.prompt.substring(0, 50)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$');

  code += `    Image(\n`;
  code += `        painter = painterResource(Res.drawable.${baseName}),\n`;
  code += `        contentDescription = "${safeDescription}",\n`;
  code += `        modifier = modifier,\n`;
  code += `        contentScale = ContentScale.Fit\n`;
  code += `    )\n`;
  code += `}\n\n`;
  
  code += `/* \nUsage Instructions:\n`;
  code += `1. Place the exported PNG in commonMain/composeResources/drawable as '${baseName}.png'.\n`;
  code += `2. Access the resource via 'Res.drawable.${baseName}'.\n`;
  code += `*/`;
  
  return code;
}
