import { GeneratedArt, AnimationSettings } from '../domain/entities';

export function generateKotlinFleksCode(art: GeneratedArt, settings: AnimationSettings): string {
  // Generate a safe variable name from the prompt
  // Take first 3 words, camelCase them
  const words = art.prompt.split(/[^a-zA-Z0-9]/).filter(w => w.length > 0).slice(0, 3);
  let safeName = 'entity';
  
  if (words.length > 0) {
    safeName = words.map((w, i) => 
      i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()
    ).join('');
  }

  const { rows, cols, targetResolution, fps } = settings;
  const totalFrames = rows * cols;
  const durationMs = Math.round(1000 / fps);
  
  // Generate frame sequence
  const framesList = Array.from({length: totalFrames}, (_, i) => i).join(', ');

  let code = `// Generated by PixelForge\n`;
  code += `val ${safeName} = world.entity {\n`;
  code += `    it += SpriteComponent(\n`;
  code += `        texture = resources.${safeName}Texture,\n`;
  code += `        slice = Slice(x = 0, y = 0, w = ${targetResolution}, h = ${targetResolution})\n`;
  code += `    )\n`;
  
  if (totalFrames > 1) {
    code += `    it += AnimationComponent(\n`;
    code += `        frames = listOf(${framesList}),\n`;
    code += `        frameDuration = ${durationMs}.milliseconds\n`;
    code += `    )\n`;
  }
  
  if (art.sliceData) {
     code += `    \n    // 9-Slice Configuration\n`;
     code += `    it += NineSliceComponent(\n`;
     code += `        top = ${art.sliceData.top}, bottom = ${art.sliceData.bottom},\n`;
     code += `        left = ${art.sliceData.left}, right = ${art.sliceData.right}\n`;
     code += `    )\n`;
  }
  
  code += `}`;
  return code;
}
